# This is a sample YAML file for fault injection configuration
# The fields here should correspond to the Fields in fiConfig.py

# Deterministic fault seed for the injections
# Seed: 1000

# Type of fault to be injected for Scalars and Tensors
# Allowed values are: {None, Rand, Zero, Rand-element, bitFlip-element, bitFlip-tensor}
#   1) None - do not inject fault
#   2) Rand - shuffle all the data items in the output of the target op into random values
#   3) Zero - change the value into all zeros
#   4) Rand-element - shuffle one of the data item in the output of the target op into random value
#   5) bitFlip-element - single bit-flip over one data item in the output of the target op
#   6) bitFlip-tensor - single bit-flip over all data items in the output of the target op 
#   7) binaryBitFlip  - binary fault injection
#   8) sequentialBitFlip  - exhaustive FI 
ScalarFaultType: None

TensorFaultType: sequentialBitFlip # use this config if you're running LeNet-allFI.py
#TensorFaultType: binaryBitFlip   # use this config if you're running LeNet-binFI.py

# Add the list of Operations and their probabilities here
# Each entry must be in a separate line ad start with a '-'
# each line must represent an OP and it's probability value
# See fiConfig.py for a full list of allowed OP values
# NOTE: These should not be any tabs anywhere below

Ops:
  - CONV2D = 1.   # This means there are two conv2d operations in the model
  - MAX-POOL = 1.
  - RELU = 1.
  - BIASADD = 1.
  - RESHAPE = 1.
  - ADD = 1.
  - MATMUL = 1.

#  - CONV2D = 1.0 # Chooses all operations
#  - LRN = 1.0
# - EQUAL = 1.0
#  - SOFT-MAX = 1.0
# - DIV = 0.0 # This does not exist - and should be ignored (Test)
# - SUB = -0.5 # This should raise an exception

# How many times the set of above operations should be skipped before injection
# SkipCount: 1


# Specify the instances of the ML operators 
# This is required when you want to specify which operator to inject (e.g., the second Conv operator).
Instances: 
  - CONV2D = 2   # This means there are two conv2d operations in the model
  - MAX-POOL = 2
  - RELU = 3
  - BIASADD = 2
  - RESHAPE = 1
  - ADD = 2
  - MATMUL = 2 


# The following lists the operators in the LeNet model, you can specify which operators to inject

# Instance starts from index 1 (14 instances in total)
# 1. CONV2D (1, 28, 28, 2) - dimension of the data in the operator is also given, the larger the more data
# 2. BIASADD (1, 28, 28, 2)
# 3. RELU (1, 28, 28, 2)
# 4. CMAXPOOL (1, 14, 14, 2)
# 5. CONV2D (1, 14, 14, 2)
# 6. BIASADD (1, 14, 14, 2)
# 7. RELU (1, 14, 14, 2)
# 8. MAXPOOL (1, 7, 7, 2)
# 9. RESHAPE (1, 98)
# 10. MATMUL (1, 32)
# 11. ADD (1, 32)
# 12. RELU (1, 32)
# 13. MATMUL (1, 10)
# 14. ADD (1, 10)

# Specify a list of target instance for injection, and the tool will inject faults into multiple operator
# For this, you need to choose the "oneFaultPerRun" mode.
TargetInstance: [13,14]  # in the current setting, in will inject the 13th operator (MATMUL) and the 14th (ADD)


# There are three inject mode:
# There are 3 ways to determine HOW to select an operation for injection"
# 1) Using error rate to determine the probability of each opertaor to be injected " 
# 2) Profiling the instance of each operation so that each operation will be injected for ONCE only" 
# 3) Perform random injection over one op per run". In this mode, you'll need to specify all the operators in the ``Instances'' section to the ``Ops'' section 
# NOTE: In the second and third mode, you'll need to fill the ``Instances'' section.

# Allowed values: 1) "errorRate"; 2) "dynamicInstance"; 3) "oneFaultPerRun" 
InjectMode: "oneFaultPerRun" 
